---
# These overrides are appropriate defaults for deploying this chart on OpenShift

server:
  standalone:
    enabled: false

  ha:
    enabled: true
    replicas: 3
    route:
      enabled: true
      activeService: true 
      #host: vault.$(oc get ingresses.config.openshift.io cluster -o jsonpath --template="{.spec.domain}")
      tls: 
        termination: edge

    raft:
      enabled: true
