kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vault-secrets-edit
  namespace: vault-server
subjects:
  - kind: ServiceAccount
    name: vault-server
    namespace: vault-server
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: secrets-edit
