apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secrets-edit
  namespace: vault-server
rules:
  - apiGroups:
      - ''
    resources:
      - secrets
    verbs:
      - create
      - get
      - list
      - patch
      - update
