{{ if .Values.vaultInit.vaultConfigOperator.installVCO }}
apiVersion: v1
kind: Namespace
metadata:
  name: vault-config-operator
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: vault-config-operator
  namespace: vault-config-operator
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/vault-config-operator.vault-config-operator: ""
  name: vault-config-operator
  namespace: vault-config-operator
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: vault-config-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
  startingCSV: vault-config-operator.v0.6.3
  config:
    env:
      - name: VAULT_ADDR
        value: "{{ .Values.vault.server.route.host }}"
{{ end }}
