apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: message
  namespace: my-app
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault
    kind: SecretStore
  target:
    name: message
  data:
  - secretKey: message
    remoteRef:
      key: my-app/message
      property: message
