---
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: demo-secret-store-template
  namespace: demo
objects:
- apiVersion: external-secrets.io/v1beta1
  kind: SecretStore
  metadata:
    name: vault
    namespace: demo
  spec:
    provider:
      vault:
        auth:
          appRole:
            path: approle
            roleId: ${ROLE_ID}
            secretRef:
              key: secret-id
              name: approle-secret
        caProvider:
          key: ca.crt
          name: kube-root-ca.crt
          type: ConfigMap
        path: secret
        readYourWrites: true
        server: "https://${VAULT_URL}"
        version: v2
parameters:
- name: ROLE_ID
  displayName: Approle RoleID
  description: Hashicopr Vault's Approle RoleID
  required: true
- name: VAULT_URL
  displayName: Hashicorp Vault URL
  description: URL of Hashicorp Vault
  required: true
