---
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: demo-secret-store-template
  namespace: demo
objects:
- apiVersion: external-secrets.io/v1beta1
  kind: SecretStore
  metadata:
    name: vault
    namespace: demo
  spec:
    provider:
      vault:
        auth:
          appRole:
            path: approle
            roleRef:
              key: role-id
              name: ${APPROLE_SECRET}
            secretRef:
              key: secret-id
              name: ${APPROLE_SECRET}
        caProvider:
          key: ca.crt
          name: kube-root-ca.crt
          type: ConfigMap
        path: secret
        readYourWrites: true
        server: 'http://vault.vault.svc.cluster.local:8200'
#        server: "${VAULT_URL}"
        version: v2
parameters:
- name: APPROLE_SECRET
  displayName: Approle's Secret
  description: Hashicorp Vault approle secret file name
  required: true
- name: VAULT_URL
  displayName: Hashicorp Vault URL
  description: URL of Hashicorp Vault
  required: true
