---
apiVersion: operator.openshift.io/v1alpha1
kind: ExternalSecretsConfig
metadata:
  name: cluster
  labels:
    app: external-secrets-operator
spec:
  controllerConfig:
    networkPolicies:
      - componentName: ExternalSecretsCoreController
        name: allow-external-secrets-egress
        egress:
          - {}
