---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vault
  namespace: demo
spec:
  dataFrom:
    - extract:
        conversionStrategy: Default
        decodingStrategy: None
        key: secret/demo
        metadataPolicy: None
        version: '1'
  refreshInterval: 15m
  secretStoreRef:
    kind: SecretStore
    name: vault
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    immutable: false
    name: demo
