---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vault
  namespace: demo
spec:
  refreshInterval: 15m
  secretStoreRef:
    name: vault
    kind: SecretStore
  target:
    name: demo
    creationPolicy: Owner
    deletionPolicy: Retain
    immutable: false
  dataFrom:
  - extract:
      key: secret/demo
      version: '1'
