# values.ha.yaml contains only the requirements to make Vault HA. Don't use
# this file on it's own. Use it in addition to values.yaml like:
# `helm install vault-server -f values.yaml -f values.ha.yaml .`
vault:
  server:
    ha:
      enabled: true
      replicas: 3
      raft:
        enabled: true
